theme: empty-jekyll-theme
excerpt_separator: '<!-- more -->'
section_separator: '<!-- section -->'
theme_bootstrap_layout:
  main: col-lg-9 offset-lg-3 col-md-9 offset-md-3 g-0 col-xl-10  offset-xl-2
  aside: col-lg-2 col-md-3 g-0
keep_files: [pagefind]
base: https://impresso-project.ch
default_author:
  title: impresso team
  slug: impresso-team
  url: /author/impresso-team
title: impresso
lang: en
languages: ['en', 'fr', 'de']
timezone: Europe/Zurich
exclude:
  - scripts
  - dep_pages
  - node_modules
  - v1.0.0
  - vendor/bundle
publisher:
  name: impresso

contacts:
  email: info @ impresso-project [dot] ch
  twitter:
    url: https://twitter.com/impressoproject
    name: '@impressoproject'
  github:
    url: https://github.com/impresso
    name: impresso
  mailinglist:
    url: https://mailchi.mp/1a05f946a602/w826p8gjtz
    name: impresso-project

collections:
  people:
    output: true
    permalink: /:collection/:path/
  partners:
    output: true
    permalink: /:collection/:path/
  glossary:
    output: true
    permalink: /:collection/:path/
  labs:
    output: true
    permalink: /:collection/:path/
  events:
    output: true
    future: true
    permalink: /:collection/:path/
  releases:
    output: true
    permalink: /:collection/:path/
  announcements:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ''
      type: events
    values:
      layout: event
  - scope:
      path: ''
      type: 'glossary'
    values:
      layout: 'glossaryItem'
  - scope:
      path: ''
      type: 'people'
    values:
      layout: 'person'
  - scope:
      path: ''
      type: 'labs'
    values:
      layout: 'labItem'
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
